gradient_accumulation_steps: 1
per_device_eval_batch_size: 4
weight_decay: 0.05
loss_type: per_sequence_loss
bf16: true
logging_steps: 1
save_total_limit: 2
save_strategy: steps
eval_strategy: steps
eval_steps: 5
data_seed: 42
warmup_steps: 0.1